default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample
  pool: 5
  username: root
  password: visvamj1
  host: localhost